# makefile

all:
	@cd 00_base_firmware; make
	@cd 01_inefficiencies; make
	@cd 02_encapsulation; make
	@cd 03_inheritance; make
	@cd 04_polymorphism; make
	@cd 05_led_blinking; make

clean:
	@cd 00_base_firmware; make clean
	@cd 01_inefficiencies; make clean
	@cd 02_encapsulation; make clean
	@cd 03_inheritance; make clean
	@cd 04_polymorphism; make clean
	@cd 05_led_blinking; make clean